# Generated by Django 5.0 on 2024-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='saveimg',
            field=models.ImageField(blank=True, null=True, upload_to='contactmage'),
        ),
    ]
